In [1]:
# 넘파이 numpy 
# 공식 홈페이지 :  https://numpy.org/

In [2]:
# 넘파이는 고성능 수치 계산을 위해 제작
# Numerical Python의 줄임말, 벡터 및 행렬 연산에 있어서 편리
# 데이터 분석을 할 때 사용하는 pandas와 matplotlib의 기반으로 사용

In [3]:
# 넘파이 배열
# 리스트는 속도가 느리고 메모리를 많이 차지함
# 배열(array)을 사용하면 적은 메모리로 많은 데이터를 빠르게 처리할 수 있음
# 파이썬 리스트 객체를 개선한 넘파이의 ndarray 객체를 사용하며 더 많은 데이터를 더 빠르게 처리할 수 있음
# 파이썬 은 자체적으로 배열 자료형을 제공하지 않기 때문에 배열을 구현한 다른 패키지를 임포트 해야함

# array라는 단위로 데이터를 관리하며 이에 대한 연산을 수행
# 넘파이의 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠름
# 벡터화 연산 vectorized operation을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있음
# 배열 인덱싱 array indexing을 사용한 질의 Query 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산할 수 있음

In [4]:
# 1. 배열 생성하기

import numpy as np

# 배열 Array란 1) 순서가 있는, 2) 같은 종류의 데이터가 저장된 집합
# 다른 종류의 데이터가 저장되면 공통된 하나의 데이터 타입으로 변경하고 성능이 떨어짐
# 정수와 실수를 같이 저장하면 정수가 실수로 변경
# 정수와 문자열을 같이 저장하면 정수가 문자열로 변경

In [5]:
# 다양한 방법으로 배열을 생성하는 방법

# 1) 시퀸스 데이터로부터 배열 생성하기. array()
# 시퀸스 데이터 seq_data를 인자로 받아 NumPy의 배열 객체 array object 생성
# arr_obj = np.array(seq_data)

# 정수 리스트로 배열 생성
data1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(data1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
array1 = np.array(data1)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(array1.dtype)

int64


In [8]:
# 정수와 실수가 혼합된 경우
data2 = [1, 2, 3, 4, 5, 6, 7, 8, 9.1]
array2 = np.array(data2)
print(array2)

[1.  2.  3.  4.  5.  6.  7.  8.  9.1]


In [9]:
print(array2.dtype) # float64. 정수와 실수가 혼합되어 있을 때 모두 실수로 변환

float64


In [10]:
# 숫자와 문자가 있는 경우
data3 = [1, 2, 3, 4, 5, 6, 7, 8, '9']
array3 = np.array(data3)
print(array3)

['1' '2' '3' '4' '5' '6' '7' '8' '9']


In [11]:
print(array3.dtype) # <U21 -> 길이가 21인 유니코드 문자열

<U21


In [13]:
# array()에 직접 리스트를 넣어서 배열 객체도 생성 가능
array4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, '9'])
print(array4)

['1' '2' '3' '4' '5' '6' '7' '8' '9']


In [14]:
# 다차원 배열의 생성 예시
array4 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
# 2) 범위를 지정해 배열 생성 arange()
# arange()를 이용해 Numpy 배열을 생성. 파이썬의 range()와 사용 방법이 비슷
# arr_obj = np.arange([start,] stop[, step])
# start부터 시작해서 stop 전까지 step만큼 계속 더해 Numpy 배열을 생성
# start가 0인 경우 생략 가능
# step이 1인 경우 생략 가능

array5 = np.arange(0, 10, 2)
print(array5)

[0 2 4 6 8]


In [16]:
array6 = np.arange(1, 10)
print(array6)

[1 2 3 4 5 6 7 8 9]


In [17]:
array7 = np.arange(5)
print(array7)

[0 1 2 3 4]


In [19]:
# Numpy 배열의 arange()를 이용해 생성한 1차원 배열에 reshape(m, n)을 추가하면 m * n 형태의 2차원 배열(행렬)로 변경
# 주의한 점은 arange()로 생성되는 배열의 원소 개수와 reshape(m, n)의 m * n의 개수가 같아야 함

array8 = np.arange(12).reshape(4, 3)
print(array8)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
# Numpy 배열의 형태를 알기 위해서는 'ndarray.shape'를 실행
print(array8.shape)

(4, 3)


In [21]:
# 1치원 배열의 경우 '(n,)'처럼 표시
print(array7.shape)

(5,)


In [24]:
# ndarray.linspace()
# 범위의 시작과 끝을 지정하고 데이터 개수를 지정해 배열을 생성
# arr_obj = np.linspace(start, stop[, num])
# linspace()는 start부터 stop까지 num개의 배열을 같은 간격으로 생성. num의 기본값은 50
array9 = np.linspace(1, 20)
print(array9)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


In [26]:
array10 = np.linspace(1, 10, 4)
print(array10)

[ 1.  4.  7. 10.]


In [28]:
# 0부터 파이까지 동일한 간격으로 20개를 나눈 배열 생성.
array11 = np.linspace(0, np.pi, 20)
print(array11)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [29]:
# 3) 특별한 형태의 배열 생성
# 모든 원소가 0 혹은 1인 다차원 배열을 만들기 위해서는 zeros()와 ones()를 이용

# 원소가 0이고 개수가 10개인 1차원 배열 생성

array12 = np.zeros(10)
print(array12)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
# 3 * 4의 2차원 배열을 생성
array13 = np.zeros((3, 4))
print(array13)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
array14 = np.ones((5, 4))
print(array14)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
# 단위행렬 Identity matrix를 생성하는 방법
# 단위행렬은 n * n인 정사각형 행렬에서 주 대각선이 모두 1이고 나머지는 0인 행렬을 의미
# arr_obj = np.eye(n)

array15 = np.eye(5) # 5 * 5 단위 행렬의 예시
print(array15)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
# 4) 배열의 데이터 타입 변환
# 배열은 숫자뿐만 아니라 문자열도 원소를 가질 수 있음

# 문자열이 원소인 배열 생성 예
a1 = np.array(['1.5', '0.62', '2', '3.14', '3.141592'])
print(a1) # ['1.5' '0.62' '2' '3.14' '3.141592']
print(a1.dtype) # <U8 데이터 형식이 유니코드이며 문자의 수는 최대 8개라는 의미

['1.5' '0.62' '2' '3.14' '3.141592']
<U8


In [1]:
# NuMPY 데이터 형식
# b : bull
# i :(singed) integer
# u : unsigned integer
# f : floating point
# c : complex-floating point
# M : datetime
# O : (Python) object
# S or a : (byte) string
# U : unicode

In [2]:
# 배열이 문자열로 표시되어 있다면 연산을 위해서는 문자열을 숫자로 변환해야 함
# 형 변환은 astype()로 가능
# num_arr = str_arr.astype(dtype)

In [5]:
# 실수가 입력된 문자열을 원소로 갖는 배열을 실수 타입으로 변환하는 예
str_a1 = np.array(['1.5', '0.62', '2', '3.14', '3.141592'])
print(str_a1)
print(str_a1.dtype)

['1.5' '0.62' '2' '3.14' '3.141592']
<U8


In [6]:
num_a1 = str_a1.astype(float)
print(num_a1)
print(num_a1.dtype)

[1.5      0.62     2.       3.14     3.141592]
float64


In [7]:
# 정수를 문자열 원소로 갖는 배열을 정수로 변환하는 예
str_a2 = np.array(['1', '6', '2', '34', '64'])
print(str_a2)
print(str_a2.dtype)

['1' '6' '2' '34' '64']
<U2


In [8]:
num_a2 = str_a2.astype(int)
print(num_a2)
print(num_a2.dtype)

[ 1  6  2 34 64]
int64


In [9]:
# 실수를 원소로 갖는 배열을 정수로 변환
num_f1 = np.array([10, 20, 30.34, 0.523, 8.22])
print(num_f1)
print(num_f1.dtype)

[10.    20.    30.34   0.523  8.22 ]
float64


In [10]:
num_i1 = num_f1.astype(int)
print(num_i1) # 값 손실이 생김
print(num_i1.dtype)

[10 20 30  0  8]
int64


In [12]:
# 5) 난수 배열의 생성
# Numpy에서 난수를 발생시킬 수 있는 다양한 함수가 있음
# rand() 함수를 이용하며 '실수 난수'를 요소로 갖는 배열을 생성
# randint() 함수를 이용하면 '정수 난수'를 요소로 갖는 배열을 생성
# rand_num = np.random.rand([d0, d1, ..., dn])
# rand_num = np.random.randint([low,] high [, size])

# rand() 함수는 [0, 1) 사이의 실수 난수를 갖는 배열을 생성 
# * [a, b)의 표현은 값의 범위가 1이상이고 b 미만이라는 의미

# randint() 함수는 [low, high) 사이의 정수 난수를 갖는 배열을 생성
# size는 배열의 형태 지정

In [14]:
print(np.random.rand())

0.8414194939170035


In [15]:
array21 = np.random.rand(10)
print(array21)

[0.17971573 0.24500497 0.56887535 0.36726024 0.13521263 0.17355703
 0.07481187 0.61903296 0.20182841 0.75637063]


In [16]:
print(np.random.rand(3, 4))

[[0.29668029 0.58654774 0.12616254 0.93868935]
 [0.10531456 0.63066295 0.34243648 0.39348939]
 [0.19990423 0.4322482  0.03513396 0.33975864]]


In [22]:
print(np.random.randint(10))

8


In [26]:
print(np.random.randint(10, 20))

10


In [27]:
print(np.random.randint(10, 20, 3))

[16 10 10]


In [28]:
# 0부터 9까지의 정수 난수를 요소로 가지는 3 * 4 배열을 생성
print(np.random.randint(10, size=(3, 4)))

[[6 9 6 5]
 [4 7 8 3]
 [2 0 5 8]]
