In [3]:
import numpy as np

# 1) 기본 연산
# 배열의 형태 shape가 같다면 덧셈과 뺄셈, 곱셈과 나눗셈 연산을 할 수 있음

In [2]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [3]:
arr3 = arr1 + arr2
print(arr3) # 각 배열의 같은 위치(인덱스)의 원소끼리 더함

[11 22 33 44]


In [4]:
print(arr1 - arr2)

[ 9 18 27 36]


In [5]:
print(arr1 * arr2)

[ 10  40  90 160]


In [6]:
print(arr1 / arr2)

[10. 10. 10. 10.]


In [8]:
# 복합 연산
print(arr1 / (arr2*2))

[5. 5. 5. 5.]


In [9]:
# 불연산. 배열은 비교 연산도 가능. 원소별로 조건과 일치하는지 검사한 후 일치하면 True를, 그렇지 않으면 False를 반환
print(arr1 > 20)

[False False  True  True]


In [1]:
# 2) 통계를 위한 연산
# Numpy에는 배열의 합, 평균, 표준편차, 분산, 최솟값과 최댓값, 누적 합과 누적 곱 등 주로 통계에서 많이 이용하는 메서드가 있음
# 각각 sum(), mean(), std(), var(), min(), max(), cumsum(), cumprod()

In [4]:
arr3 = np.arange(5)
print(arr3)

[0 1 2 3 4]


In [5]:
# 합
print(arr3.sum())

10


In [6]:
# 평균
print(arr3.mean())

2.0


In [7]:
# 표준편차
print(arr3.std())

1.4142135623730951


In [8]:
# 분산
print(arr3.var())

2.0


In [9]:
# 최솟값
print(arr3.min())

0


In [10]:
# 최댓값
print(arr3.max())

4


In [11]:
arr4 = np.arange(1, 5)
print(arr4)

[1 2 3 4]


In [12]:
# 누적 합
print(arr4.cumsum())

[ 1  3  6 10]


In [13]:
# 누적 곱
print(arr4.cumprod())

[ 1  2  6 24]
