In [1]:
import numpy as np

# 인덱싱 Indexing : 배열의 위치나 조건을 지정해 배열의 원소를 선택
# 슬라이싱 Slicing : 범위를 지정해 배열의 원소를 선택

In [2]:
# 1) 배열의 인덱싱
# 1차원 배열에서 특정 위치의 원소를 선택하려면 원소의 위치를 지정
# 배열명[위치]
# 배열 원소의 위치는 0부터 시작

arr1 = np.array([0, 10, 20, 30, 40, 50])
arr1

array([ 0, 10, 20, 30, 40, 50])

In [3]:
print(arr1[0])
print(arr1[4])

0
40


In [4]:
# -인덱스도 사용가능
print(arr1[-2])

40


In [5]:
# 배열을 변경
arr1[-1] = 70
print(arr1)

[ 0 10 20 30 40 70]


In [7]:
# 배열명[위치1, 위치2, ..., 위치n]
print(arr1[[1, 3, 5]])

[10 30 70]


In [13]:
# 2차원 배열에서 특정 위치의 원소를 선택하려면 행과 열의 위치를 지정
# 배열명[행_위치, 열_위치]

# 10부터 99까지 10씩 증가하는 1차원 배열(개수가 9개)을 생성한 후에 3행 3열의 2차원 배열로 모양을 바꿈
arr2 = np.arange(10, 100, 10).reshape((3, 3))
print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [14]:
print(arr2[0])

[10 20 30]


In [16]:
# 행위치가 0이고, 열위치가 2인 원소를 반환
print(arr2[0][2])
print(arr2[(0, 2)])

30
30


In [17]:
# 2차원 배령의 행과 열의 위치를 지정해서 원소를 선택한 후 값을 변경할 수 있음
arr2[2][2] = 95
print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 95]]


In [18]:
# 행위치만 지정하면 행 전체를 가져옴
print(arr2[1])

[40 50 60]


In [19]:
# 2차원 배열의 특정 행을 지정해서 행 전체를 변경할 수 있음
# 새로운 값을 입력할 때 np.array(seq_data)
arr2[1] = [45,55,65]
print(arr2)

[[10 20 30]
 [45 55 65]
 [70 80 95]]


In [20]:
arr2[1] = [47,57,67]
print(arr2)

[[10 20 30]
 [47 57 67]
 [70 80 95]]


In [24]:
# 2차원 배열의 여러 원소를 선택ㄷ하기 위해서 아래와 같이 지정
# 배열명[[행_위치1, 행_위치2, ..., 행_위치n], [열_위치1, 열_위치2, ..., 열_위치n]]

print(arr2[[0, 2], [0, 1]]) # arr2[0][0], arr[2][1]

[10 80]


In [27]:
# 배열에 조건을 지정해 조건을 만족하는 배열을 선택
# 배열명[조건]

arr3 = np.array([1, 5, 3, 4, 2, 6])
print(arr3)

[1 5 3 4 2 6]


In [28]:
print(arr3 > 3)

[False  True False  True False  True]


In [29]:
arr4 = arr3[arr3 > 3]
print(arr4)

[5 4 6]


In [31]:
# 짝수만 선택하는 예
print(arr3 % 2 == 0)
print(arr3[arr3 % 2 == 0])

[False False False  True  True  True]
[4 2 6]
